### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by perdidor** [nopnop2002/esp-idf-sc16is750#2]
Hello.
First, thanks for sharing your work.
Could you please explain me something. I see everywhere in component code WiringPi functions calls. Seems like you tested it on RPi, or there is a wiringPi lib for ESP32? - i cant find(
Thanks.

**Comment by nopnop2002** [comment]
There is no call to the WiringPi function anywhere.
There is no wiringPi library for ESP32.

Are you using ESP-IDF?
https://github.com/espressif/esp-idf

**Comment by perdidor** [comment]
ooh sorry seems i messed with all this stuff as espressif has a lot of branches/versions etc... Sorry again, close please this issue. Thanks.
